import { StyleSheet } from 'react-native';
import { CyberPunkTheme } from '../constants/theme';

const { colors, spacing, radius, shadows, typography } = CyberPunkTheme;

export const cardStyles = StyleSheet.create({
  cardContainer: {
    marginBottom: spacing['3xl'],
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius['2xl'],
    padding: spacing['3xl'],
    borderLeftWidth: 6,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: colors.glass,
    borderRightColor: colors.glass,
    borderBottomColor: colors.glass,
    width: '100%',
    ...shadows.neon,
  },
  headerSection: {
    marginBottom: spacing['2xl'],
    alignItems: 'center',
  },
  profileSection: {
    alignItems: 'center',
    width: '100%',
  },
  avatarContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: spacing['2xl'],
    overflow: 'hidden',
    backgroundColor: colors.surfaceLight,
    borderWidth: 4,
    borderColor: colors.primary,
    ...shadows.neon,
    shadowColor: colors.primary,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    resizeMode: 'cover',
  },
  imageLoadingOverlay: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fallbackAvatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.surfaceLight,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
  },
  avatarText: {
    fontSize: typography.sizes['4xl'],
    fontWeight: typography.weights.black,
    color: colors.textPrimary,
    textShadowColor: colors.primary,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  nameSection: {
    alignItems: 'center',
    width: '100%',
  },
  name: {
    fontSize: typography.sizes['3xl'],
    fontWeight: typography.weights.black,
    marginBottom: spacing.sm,
    color: colors.textPrimary,
    lineHeight: 34,
    textAlign: 'center',
    letterSpacing: -0.5,
    textShadowColor: colors.primaryDark,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  title: {
    fontSize: typography.sizes.xl,
    fontWeight: typography.weights.bold,
    color: colors.primary,
    marginBottom: spacing.lg,
    lineHeight: 26,
    textAlign: 'center',
    textShadowColor: colors.primaryDark,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  universityBadge: {
    backgroundColor: colors.surfaceLight,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.xl,
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
    ...shadows.neon,
    shadowColor: colors.primary,
  },
  universityText: {
    fontSize: typography.sizes.sm,
    fontWeight: typography.weights.extrabold,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    textAlign: 'center',
  },
});
